openapi: 3.0.1
info:
  title: postman api rbih
  description: ''
  version: 1.0.0
tags: []
paths:
  /:
    get:
      summary: Get Subdivnumber
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: client-id
          in: header
          description: ''
          required: true
          example: '{{client_id}}'
          schema:
            type: string
        - name: txncode
          in: header
          description: ''
          required: true
          example: '{{txncode}}'
          schema:
            type: string
        - name: provider
          in: header
          description: ''
          required: true
          example: '{{provider}}'
          schema:
            type: string
        - name: servicename
          in: header
          description: ''
          required: true
          example: '{{servicename}}'
          schema:
            type: string
        - name: ts
          in: header
          description: ''
          required: true
          example: '{{currentdate}}'
          schema:
            type: string
        - name: lgdcode
          in: header
          description: ''
          required: true
          example: '{{lgdcode}}'
          schema:
            type: string
        - name: surveynumber
          in: header
          description: ''
          required: true
          example: '{{surveynumber}}'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      errcode:
                        type: string
                      status:
                        type: string
                      info:
                        type: string
                    required:
                      - errcode
                      - status
                      - info
                  data:
                    type: object
                    properties:
                      sub_division_numbers:
                        type: array
                        items:
                          type: object
                          properties:
                            sub_division_number:
                              type: string
                          required:
                            - sub_division_number
                    required:
                      - sub_division_numbers
                  signature:
                    type: string
                  meta:
                    type: object
                    properties:
                      txncode:
                        type: string
                      ver:
                        type: string
                      ts:
                        type: string
                    required:
                      - txncode
                      - ver
                      - ts
                  hmac:
                    type: string
                  publickey:
                    type: string
                  sig-algo:
                    type: string
                required:
                  - result
                  - data
                  - signature
                  - meta
                  - hmac
                  - publickey
                  - sig-algo
              example:
                result:
                  errcode: E000
                  status: success
                  info: ''
                data:
                  sub_division_numbers:
                    - sub_division_number: '1'
                    - sub_division_number: 10A
                    - sub_division_number: '11'
                    - sub_division_number: '12'
                    - sub_division_number: 13A
                    - sub_division_number: '14'
                    - sub_division_number: 15B
                    - sub_division_number: '16'
                    - sub_division_number: '17'
                    - sub_division_number: '18'
                    - sub_division_number: 19A1
                    - sub_division_number: 19A5
                    - sub_division_number: '2'
                    - sub_division_number: 3A1A
                    - sub_division_number: 3A2
                    - sub_division_number: 3B
                    - sub_division_number: 3C
                    - sub_division_number: '9'
                signature: >-
                  MGYCMQCwDqMPTUNnhl6WONf9mXSyLxrdPDzA5PAOHSLfzU7KVeEaVboZR0ArAsvXAD3lL+wCMQCH08ZtBuNGlQnfVG9JxlVu6Hl25MR46hdpHo4l0+DwzQtlFcus8446s33rQ3RaBOI=
                meta:
                  txncode: '34456'
                  ver: '1.0'
                  ts: 2025-08-01T12:32:21+0530
                hmac: vn5djg8pnDz/tvjWWxszFxrscoUG3shhN4Hz5ghQrBA=
                publickey: >-
                  MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEetPVO7LgXhpaTBnXN7aIW3v6Lxzd22KGyZ+5wiIRiZmyv18Y1SWCCU2T8IpHOTbIZfpdb+CBE4xjkjrsFYp2CI84XVX0cSgObQ8ymcSRgvYPyeq6rgOXb3upjTxMRFII
                sig-algo: SHA256withECDSA
          headers: {}
        x-200:Failed:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      errcode:
                        type: string
                      status:
                        type: string
                      info:
                        type: string
                    required:
                      - errcode
                      - status
                      - info
                  data:
                    type: object
                    properties: {}
                  signature:
                    type: string
                  meta:
                    type: object
                    properties:
                      txncode:
                        type: string
                      ver:
                        type: string
                      ts:
                        type: string
                    required:
                      - txncode
                      - ver
                      - ts
                  hmac:
                    type: string
                  publickey:
                    type: string
                  sig-algo:
                    type: string
                required:
                  - result
                  - data
                  - signature
                  - meta
                  - hmac
                  - publickey
                  - sig-algo
              example:
                result:
                  errcode: E515
                  status: failed
                  info: Invalid lgdcode value
                data: {}
                signature: >-
                  MGUCMQDd1ko3+2v6i6NJfH7fzoNzTUu9FJsCoYre2EH5pzjLAvVzfKw+FXwLelQKD3DyFdkCMAnppAuBHNpvrMWdYIVd22X6FO4NHhviNOFidH9OAVEcJs18eL3fuCQDhh1GmG04sA==
                meta:
                  txncode: '34456'
                  ver: '1.0'
                  ts: 2025-08-01T12:32:48+0530
                hmac: WKljGvYklRgU3reW7KNmUGa2W55zRF/8b/bnw/JWYo4=
                publickey: >-
                  MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEFmiPObOoAPa4yuwlQeMJateSMomQemgQ78rphhwHBtzhAwPAjfF6wUPTADtsztPySglHN2tM456RV0zcCKw21pXVLQwZnqhJOz6zZNaw4KjgDyVvSOF2NZ53O+SrJuVF
                sig-algo: SHA256withECDSA
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
security: []
